/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ModelSetsRouteImport } from './routes/model-sets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminOrganizationRouteImport } from './routes/admin/organization'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminChatsRouteImport } from './routes/admin/chats'
import { Route as AdminBrainsRouteImport } from './routes/admin/brains'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminChatsChatIdRouteImport } from './routes/admin/chats.$chatId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelSetsRoute = ModelSetsRouteImport.update({
  id: '/model-sets',
  path: '/model-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LessonsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrainsRoute = AdminBrainsRouteImport.update({
  id: '/brains',
  path: '/brains',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminChatsChatIdRoute = AdminChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AdminChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brain'
    | '/chat'
    | '/lessons'
    | '/login'
    | '/model-sets'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/shared/$token'
    | '/projects/'
    | '/admin/'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/chat'
    | '/lessons'
    | '/login'
    | '/model-sets'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/shared/$token'
    | '/admin'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brain'
    | '/chat'
    | '/lessons'
    | '/login'
    | '/model-sets'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/shared/$token'
    | '/projects/'
    | '/admin/'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BrainRoute: typeof BrainRoute
  ChatRoute: typeof ChatRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModelSetsRoute: typeof ModelSetsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-sets': {
      id: '/model-sets'
      path: '/model-sets'
      fullPath: '/model-sets'
      preLoaderRoute: typeof ModelSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brains': {
      id: '/admin/brains'
      path: '/brains'
      fullPath: '/admin/brains'
      preLoaderRoute: typeof AdminBrainsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/chats/$chatId': {
      id: '/admin/chats/$chatId'
      path: '/$chatId'
      fullPath: '/admin/chats/$chatId'
      preLoaderRoute: typeof AdminChatsChatIdRouteImport
      parentRoute: typeof AdminChatsRoute
    }
  }
}

interface AdminChatsRouteChildren {
  AdminChatsChatIdRoute: typeof AdminChatsChatIdRoute
}

const AdminChatsRouteChildren: AdminChatsRouteChildren = {
  AdminChatsChatIdRoute: AdminChatsChatIdRoute,
}

const AdminChatsRouteWithChildren = AdminChatsRoute._addFileChildren(
  AdminChatsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrainsRoute: typeof AdminBrainsRoute
  AdminChatsRoute: typeof AdminChatsRouteWithChildren
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBrainsRoute: AdminBrainsRoute,
  AdminChatsRoute: AdminChatsRouteWithChildren,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LessonsRouteChildren {
  LessonsIdRoute: typeof LessonsIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsIdRoute: LessonsIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BrainRoute: BrainRoute,
  ChatRoute: ChatRoute,
  LessonsRoute: LessonsRouteWithChildren,
  LoginRoute: LoginRoute,
  ModelSetsRoute: ModelSetsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
