/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelSetsRouteImport } from './routes/model-sets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ScrapingRouteRouteImport } from './routes/scraping.route'
import { Route as ProjectsRouteRouteImport } from './routes/projects.route'
import { Route as LessonsRouteRouteImport } from './routes/lessons.route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrapingIndexRouteImport } from './routes/scraping.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as ScrapingNewRouteImport } from './routes/scraping.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminOrganizationRouteImport } from './routes/admin/organization'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminChatsRouteImport } from './routes/admin/chats'
import { Route as AdminBrainsRouteImport } from './routes/admin/brains'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as ScrapingMissionIdRouteRouteImport } from './routes/scraping.$missionId.route'
import { Route as ScrapingMissionIdIndexRouteImport } from './routes/scraping.$missionId.index'
import { Route as ScrapingMissionIdBlueprintRouteImport } from './routes/scraping.$missionId.blueprint'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminChatsChatIdRouteImport } from './routes/admin/chats.$chatId'
import { Route as ScrapingMissionIdRunsRouteRouteImport } from './routes/scraping.$missionId.runs.route'
import { Route as ScrapingMissionIdRunsIndexRouteImport } from './routes/scraping.$missionId.runs.index'
import { Route as ScrapingMissionIdRunsRunIdRouteImport } from './routes/scraping.$missionId.runs.$runId'
import { Route as ScrapingMissionIdExecutionsExecutionIdRouteImport } from './routes/scraping.$missionId.executions.$executionId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelSetsRoute = ModelSetsRouteImport.update({
  id: '/model-sets',
  path: '/model-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapingRouteRoute = ScrapingRouteRouteImport.update({
  id: '/scraping',
  path: '/scraping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRouteRoute = LessonsRouteRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapingIndexRoute = ScrapingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScrapingRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapingNewRoute = ScrapingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScrapingRouteRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LessonsRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrainsRoute = AdminBrainsRouteImport.update({
  id: '/brains',
  path: '/brains',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ScrapingMissionIdRouteRoute = ScrapingMissionIdRouteRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => ScrapingRouteRoute,
} as any)
const ScrapingMissionIdIndexRoute = ScrapingMissionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScrapingMissionIdRouteRoute,
} as any)
const ScrapingMissionIdBlueprintRoute =
  ScrapingMissionIdBlueprintRouteImport.update({
    id: '/blueprint',
    path: '/blueprint',
    getParentRoute: () => ScrapingMissionIdRouteRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminChatsChatIdRoute = AdminChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AdminChatsRoute,
} as any)
const ScrapingMissionIdRunsRouteRoute =
  ScrapingMissionIdRunsRouteRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => ScrapingMissionIdRouteRoute,
  } as any)
const ScrapingMissionIdRunsIndexRoute =
  ScrapingMissionIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ScrapingMissionIdRunsRouteRoute,
  } as any)
const ScrapingMissionIdRunsRunIdRoute =
  ScrapingMissionIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ScrapingMissionIdRunsRouteRoute,
  } as any)
const ScrapingMissionIdExecutionsExecutionIdRoute =
  ScrapingMissionIdExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => ScrapingMissionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lessons': typeof LessonsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/scraping': typeof ScrapingRouteRouteWithChildren
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/scraping/$missionId': typeof ScrapingMissionIdRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scraping/new': typeof ScrapingNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scraping/': typeof ScrapingIndexRoute
  '/scraping/$missionId/runs': typeof ScrapingMissionIdRunsRouteRouteWithChildren
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/scraping/$missionId/blueprint': typeof ScrapingMissionIdBlueprintRoute
  '/scraping/$missionId/': typeof ScrapingMissionIdIndexRoute
  '/scraping/$missionId/executions/$executionId': typeof ScrapingMissionIdExecutionsExecutionIdRoute
  '/scraping/$missionId/runs/$runId': typeof ScrapingMissionIdRunsRunIdRoute
  '/scraping/$missionId/runs/': typeof ScrapingMissionIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scraping/new': typeof ScrapingNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin': typeof AdminIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/scraping': typeof ScrapingIndexRoute
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/scraping/$missionId/blueprint': typeof ScrapingMissionIdBlueprintRoute
  '/scraping/$missionId': typeof ScrapingMissionIdIndexRoute
  '/scraping/$missionId/executions/$executionId': typeof ScrapingMissionIdExecutionsExecutionIdRoute
  '/scraping/$missionId/runs/$runId': typeof ScrapingMissionIdRunsRunIdRoute
  '/scraping/$missionId/runs': typeof ScrapingMissionIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lessons': typeof LessonsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/scraping': typeof ScrapingRouteRouteWithChildren
  '/brain': typeof BrainRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/model-sets': typeof ModelSetsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/scraping/$missionId': typeof ScrapingMissionIdRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brains': typeof AdminBrainsRoute
  '/admin/chats': typeof AdminChatsRouteWithChildren
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/lessons/$id': typeof LessonsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scraping/new': typeof ScrapingNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scraping/': typeof ScrapingIndexRoute
  '/scraping/$missionId/runs': typeof ScrapingMissionIdRunsRouteRouteWithChildren
  '/admin/chats/$chatId': typeof AdminChatsChatIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/scraping/$missionId/blueprint': typeof ScrapingMissionIdBlueprintRoute
  '/scraping/$missionId/': typeof ScrapingMissionIdIndexRoute
  '/scraping/$missionId/executions/$executionId': typeof ScrapingMissionIdExecutionsExecutionIdRoute
  '/scraping/$missionId/runs/$runId': typeof ScrapingMissionIdRunsRunIdRoute
  '/scraping/$missionId/runs/': typeof ScrapingMissionIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lessons'
    | '/projects'
    | '/scraping'
    | '/brain'
    | '/chat'
    | '/login'
    | '/model-sets'
    | '/settings'
    | '/templates'
    | '/scraping/$missionId'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/scraping/new'
    | '/shared/$token'
    | '/admin/'
    | '/lessons/'
    | '/projects/'
    | '/scraping/'
    | '/scraping/$missionId/runs'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
    | '/scraping/$missionId/blueprint'
    | '/scraping/$missionId/'
    | '/scraping/$missionId/executions/$executionId'
    | '/scraping/$missionId/runs/$runId'
    | '/scraping/$missionId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/chat'
    | '/login'
    | '/model-sets'
    | '/settings'
    | '/templates'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/scraping/new'
    | '/shared/$token'
    | '/admin'
    | '/lessons'
    | '/projects'
    | '/scraping'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
    | '/scraping/$missionId/blueprint'
    | '/scraping/$missionId'
    | '/scraping/$missionId/executions/$executionId'
    | '/scraping/$missionId/runs/$runId'
    | '/scraping/$missionId/runs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lessons'
    | '/projects'
    | '/scraping'
    | '/brain'
    | '/chat'
    | '/login'
    | '/model-sets'
    | '/settings'
    | '/templates'
    | '/scraping/$missionId'
    | '/admin/audit'
    | '/admin/brains'
    | '/admin/chats'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/organization'
    | '/admin/projects'
    | '/admin/security'
    | '/admin/usage'
    | '/admin/users'
    | '/lessons/$id'
    | '/projects/$id'
    | '/scraping/new'
    | '/shared/$token'
    | '/admin/'
    | '/lessons/'
    | '/projects/'
    | '/scraping/'
    | '/scraping/$missionId/runs'
    | '/admin/chats/$chatId'
    | '/admin/users/$userId'
    | '/scraping/$missionId/blueprint'
    | '/scraping/$missionId/'
    | '/scraping/$missionId/executions/$executionId'
    | '/scraping/$missionId/runs/$runId'
    | '/scraping/$missionId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LessonsRouteRoute: typeof LessonsRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  ScrapingRouteRoute: typeof ScrapingRouteRouteWithChildren
  BrainRoute: typeof BrainRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  ModelSetsRoute: typeof ModelSetsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-sets': {
      id: '/model-sets'
      path: '/model-sets'
      fullPath: '/model-sets'
      preLoaderRoute: typeof ModelSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraping': {
      id: '/scraping'
      path: '/scraping'
      fullPath: '/scraping'
      preLoaderRoute: typeof ScrapingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraping/': {
      id: '/scraping/'
      path: '/'
      fullPath: '/scraping/'
      preLoaderRoute: typeof ScrapingIndexRouteImport
      parentRoute: typeof ScrapingRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof LessonsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraping/new': {
      id: '/scraping/new'
      path: '/new'
      fullPath: '/scraping/new'
      preLoaderRoute: typeof ScrapingNewRouteImport
      parentRoute: typeof ScrapingRouteRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof LessonsRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brains': {
      id: '/admin/brains'
      path: '/brains'
      fullPath: '/admin/brains'
      preLoaderRoute: typeof AdminBrainsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/scraping/$missionId': {
      id: '/scraping/$missionId'
      path: '/$missionId'
      fullPath: '/scraping/$missionId'
      preLoaderRoute: typeof ScrapingMissionIdRouteRouteImport
      parentRoute: typeof ScrapingRouteRoute
    }
    '/scraping/$missionId/': {
      id: '/scraping/$missionId/'
      path: '/'
      fullPath: '/scraping/$missionId/'
      preLoaderRoute: typeof ScrapingMissionIdIndexRouteImport
      parentRoute: typeof ScrapingMissionIdRouteRoute
    }
    '/scraping/$missionId/blueprint': {
      id: '/scraping/$missionId/blueprint'
      path: '/blueprint'
      fullPath: '/scraping/$missionId/blueprint'
      preLoaderRoute: typeof ScrapingMissionIdBlueprintRouteImport
      parentRoute: typeof ScrapingMissionIdRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/chats/$chatId': {
      id: '/admin/chats/$chatId'
      path: '/$chatId'
      fullPath: '/admin/chats/$chatId'
      preLoaderRoute: typeof AdminChatsChatIdRouteImport
      parentRoute: typeof AdminChatsRoute
    }
    '/scraping/$missionId/runs': {
      id: '/scraping/$missionId/runs'
      path: '/runs'
      fullPath: '/scraping/$missionId/runs'
      preLoaderRoute: typeof ScrapingMissionIdRunsRouteRouteImport
      parentRoute: typeof ScrapingMissionIdRouteRoute
    }
    '/scraping/$missionId/runs/': {
      id: '/scraping/$missionId/runs/'
      path: '/'
      fullPath: '/scraping/$missionId/runs/'
      preLoaderRoute: typeof ScrapingMissionIdRunsIndexRouteImport
      parentRoute: typeof ScrapingMissionIdRunsRouteRoute
    }
    '/scraping/$missionId/runs/$runId': {
      id: '/scraping/$missionId/runs/$runId'
      path: '/$runId'
      fullPath: '/scraping/$missionId/runs/$runId'
      preLoaderRoute: typeof ScrapingMissionIdRunsRunIdRouteImport
      parentRoute: typeof ScrapingMissionIdRunsRouteRoute
    }
    '/scraping/$missionId/executions/$executionId': {
      id: '/scraping/$missionId/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/scraping/$missionId/executions/$executionId'
      preLoaderRoute: typeof ScrapingMissionIdExecutionsExecutionIdRouteImport
      parentRoute: typeof ScrapingMissionIdRouteRoute
    }
  }
}

interface AdminChatsRouteChildren {
  AdminChatsChatIdRoute: typeof AdminChatsChatIdRoute
}

const AdminChatsRouteChildren: AdminChatsRouteChildren = {
  AdminChatsChatIdRoute: AdminChatsChatIdRoute,
}

const AdminChatsRouteWithChildren = AdminChatsRoute._addFileChildren(
  AdminChatsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrainsRoute: typeof AdminBrainsRoute
  AdminChatsRoute: typeof AdminChatsRouteWithChildren
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBrainsRoute: AdminBrainsRoute,
  AdminChatsRoute: AdminChatsRouteWithChildren,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LessonsRouteRouteChildren {
  LessonsIdRoute: typeof LessonsIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

const LessonsRouteRouteChildren: LessonsRouteRouteChildren = {
  LessonsIdRoute: LessonsIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}

const LessonsRouteRouteWithChildren = LessonsRouteRoute._addFileChildren(
  LessonsRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface ScrapingMissionIdRunsRouteRouteChildren {
  ScrapingMissionIdRunsRunIdRoute: typeof ScrapingMissionIdRunsRunIdRoute
  ScrapingMissionIdRunsIndexRoute: typeof ScrapingMissionIdRunsIndexRoute
}

const ScrapingMissionIdRunsRouteRouteChildren: ScrapingMissionIdRunsRouteRouteChildren =
  {
    ScrapingMissionIdRunsRunIdRoute: ScrapingMissionIdRunsRunIdRoute,
    ScrapingMissionIdRunsIndexRoute: ScrapingMissionIdRunsIndexRoute,
  }

const ScrapingMissionIdRunsRouteRouteWithChildren =
  ScrapingMissionIdRunsRouteRoute._addFileChildren(
    ScrapingMissionIdRunsRouteRouteChildren,
  )

interface ScrapingMissionIdRouteRouteChildren {
  ScrapingMissionIdRunsRouteRoute: typeof ScrapingMissionIdRunsRouteRouteWithChildren
  ScrapingMissionIdBlueprintRoute: typeof ScrapingMissionIdBlueprintRoute
  ScrapingMissionIdIndexRoute: typeof ScrapingMissionIdIndexRoute
  ScrapingMissionIdExecutionsExecutionIdRoute: typeof ScrapingMissionIdExecutionsExecutionIdRoute
}

const ScrapingMissionIdRouteRouteChildren: ScrapingMissionIdRouteRouteChildren =
  {
    ScrapingMissionIdRunsRouteRoute:
      ScrapingMissionIdRunsRouteRouteWithChildren,
    ScrapingMissionIdBlueprintRoute: ScrapingMissionIdBlueprintRoute,
    ScrapingMissionIdIndexRoute: ScrapingMissionIdIndexRoute,
    ScrapingMissionIdExecutionsExecutionIdRoute:
      ScrapingMissionIdExecutionsExecutionIdRoute,
  }

const ScrapingMissionIdRouteRouteWithChildren =
  ScrapingMissionIdRouteRoute._addFileChildren(
    ScrapingMissionIdRouteRouteChildren,
  )

interface ScrapingRouteRouteChildren {
  ScrapingMissionIdRouteRoute: typeof ScrapingMissionIdRouteRouteWithChildren
  ScrapingNewRoute: typeof ScrapingNewRoute
  ScrapingIndexRoute: typeof ScrapingIndexRoute
}

const ScrapingRouteRouteChildren: ScrapingRouteRouteChildren = {
  ScrapingMissionIdRouteRoute: ScrapingMissionIdRouteRouteWithChildren,
  ScrapingNewRoute: ScrapingNewRoute,
  ScrapingIndexRoute: ScrapingIndexRoute,
}

const ScrapingRouteRouteWithChildren = ScrapingRouteRoute._addFileChildren(
  ScrapingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LessonsRouteRoute: LessonsRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  ScrapingRouteRoute: ScrapingRouteRouteWithChildren,
  BrainRoute: BrainRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  ModelSetsRoute: ModelSetsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
